### ISSUE TITLE
tab through is broken for firefox and safairi on the bulk downloads index

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-transition#160]
Here is the page:
https://www.fec.gov/files/bulk-downloads/index.html

Tabbing through works on chrome but doesn't seem to work on other browsers. This is a 508 issue.

**Comment by jcarbaugh** [comment]
It's a macOS thing - there's nothing you can do. Safari defaults to Option-Tab instead of just Tab (unless overridden in Preferences > Advanced > "Press Tab to highlight...") and it works quite well. Similarly, Firefox requires a change in [System Preferences AND a new setting in about:config](https://stackoverflow.com/a/11713537) to make Tab selection work... and work it does on this page, once those are set.

Keep up the amazing work!

**Comment by LindsayYoung** [comment]
Thanks! @jcarbaugh
