### ISSUE TITLE
Check GSA security review of Invision for prototyping tool for FEC

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#176]
What we're after:
In order to use Invision as a prototyping tool, we need to check GSA security review of Invision. (Is it GSA provisional?)

- [ ] Check on GSA security status for Invision

**Comment by jenniferthibault** [comment]
I've found that InVision (without sync) is approved for use at GSA!

The paper trail is a little confusing since the security review references an ATO through 9/2018, but it's not an _actual_ ATO, more of an "Authorized to Use", as our infrastructure team has helped me understand.

My next steps are to forward the documentation that I found to @JayRibeiro by email, and see what magic he can make of it or what additional information might be needed.

**Comment by AmyKort** [comment]
Great news!

**Comment by jenniferthibault** [comment]
Jay fully recommend approval of InVision without sync as approved by GSA, and it's being moved to FEC's approved software list. 

We haven't been using sync (since it's not allowed at GSA) anyways so we shouldn't be affected by that limit. Closing this ticket in favor of https://github.com/18F/fec-transition/issues/179 as a next step to procure licenses for the team.
