### ISSUE TITLE
Define Role of Core Team Member(s) - Design

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-transition#3]
The FEC needs to understand the role of a design person so that they can:
- Identify people who would be interested and have the ability to do the job
- Identify the need to hire and describe the position

Given the design chapter is such a vast discipline at 18F encompassing:
- Research
- UX
- Visual Design
- Content

Perhaps we focus on describing the roles which could be filled by 1 or more people.

The goal of this story is to create a write up describing the day-day activites and skills required of a person filling this role.

A few things to consider when creating this write up:
- Design charter
- Join 18F position descriptions
- Design Method cards
- "A day/sprint in the life of a design person"

**Comment by jenniferthibault** [comment]
I set up the template to get started here:
https://github.com/18F/fec-transition/wiki/Design-Role-Description

Resources:
[Design Capabilities Deck](https://docs.google.com/presentation/d/1aOeq5SsLSMhskchlJRtSLQ28OcIzAQgkanyDZy7bPiU/edit?ts=56f9ae68#slide=id.g10cad4ffb6_0_198)

I had capacity to start working on tit this morning, but it's unclear to me if we need to make one position, or describe each of our roles as they are now. 

@noahmanger @onezerojeremy let's huddle up so that we can get a draft of this going. Porta would like to have it by the end of the week. Once we're aligned on what we're trying to put together, I can take the first stab at grafting everything together.

**Comment by jenniferthibault** [comment]
@noahmanger & @onezerojeremy : first draft is up here, please review. 
https://github.com/18F/fec-transition/wiki/Design-Role-Description
