### ISSUE TITLE
Cloud.gov FEC application deployment workshop

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#31]
Give a workshop to the FEC integration team on how to deploy 18F developed FEC applications to cloud.gov.

**Comment by adrianwebb** [comment]
Start with the application that is easiest to deploy first.

**Comment by ccostino** [comment]
There are multiple ways to look at this as all of the applications are relatively easy to deploy since they're all deployed the same way. :-)  That said, we have the following pieces we could cover, though each does build on the last to some degree:

* Doing a manual push of a cloud.gov application and how the manifest file(s) ties into that (and where to find all of the documentation).
* Doing a semi-automated push using the `autopilot` plugin and our `invoke` tasks (builds on the manual push material).
* How we have automated deployments configured via Travis and `git flow`'s use of tags (builds a bit on the semi-automated push).

We could also cover how the applications are tied to one another in the deployment setup, how to find and read the logs to troubleshoot deployment issues, and how the services are tied to the applications, but I recognize going over all of these things might be too much in a single session.

**Comment by adrianwebb** [comment]
Yeah, I like all of these :-)   But I agree completely.  It might make sense to walk them through the manual process first, then we can build on top of that to show the automation processes.

I definitely think we should cover the linkage of the applications being deployed.

**Comment by adrianwebb** [comment]
Treating as a unified training with the GitHub training: https://github.com/18F/fec-transition/issues/30
