### ISSUE TITLE
Define Role of Core Team Member - Technical Lead

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-transition#4]
The FEC needs to understand the role of a technical lead so that they can:
- Identify people who would be interested and have the ability to do the job
- Identify the need to hire and describe the position

The goal of this story is to create a write up describing the day-day activities and skills required of a person filling this role.

A few things to consider when creating this write up:
- Engineering lead/facilitator guides
- Join 18F position descriptions
- "A day/sprint in the life of an engineering lead"

**Comment by adrianwebb** [comment]
I have a good start here:

https://github.com/18F/fec-transition/wiki/Technical-Role-Description

I added a section "Key Characteristics" because I did not feel that the characteristics, commonly embodied in DevOps, could be fit in elsewhere.  And I think it is important to call out those characteristics as part of the profile.

I have a question though.  Is this position referring to a portfolio level technical lead or the technical component of a product team?  The reason I ask is that I do not know how hands on this lead is supposed to get.  

If it is a "digital services team" kind of tech lead I would have them more guidance and oversight.  If they are more product delivery focused they might need to be much more hands on with development of the product, depending on team size or contractors available.

This question really drives the answer to "A Sprint in the Life Of A Technical Lead".

**Comment by porta-antiporta** [comment]
My $.02 is that we start small and hands-on. As this team gains momentum the role could be more high level. So my thoughts was more of a technical lead for a team (or two).  That being said look to @ccostino and @adborden to weigh in as they're much closer to the action...
