### ISSUE TITLE
Provide FEC information about the legal issues associated with recruiting users

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#44]
Provide information to the FEC about PRA and PII

**Comment by nickykrause** [comment]
Okay, @patphongs: I looked into it after our conversation today, and I wanted to send you a quick note about the Paperwork Reduction Act (PRA), which I said has implications for how 18F conducts its recruiting practices and its research.

I am certainly not a lawyer, but the statue appears to suggest that the FEC is exempt from PRA restrictions. Here is what I could find:



> As used in this subchapter— (1) the term “agency” means any executive department, military department, Government corporation, Government controlled corporation, or other establishment in the executive branch of the Government (including the Executive Office of the President), or any independent regulatory agency, but does not include—
> (A) the Government Accountability Office;
> **(B) Federal Election Commission;**
> (C) the governments of the District of Columbia and of the territories and possessions of the United States, and their various subdivisions; or
> (D) Government-owned contractor-operated facilities, including laboratories engaged in national defense research and production activities;

Quoted from: https://www.law.cornell.edu/uscode/text/44/3502, in the larger context of https://www.law.cornell.edu/uscode/text/44/3501. 

If this is true, then it seems that you won't have to worry about PRA, and, consequently, I won't need to provide you with information as to how 18F addresses PRA concerns (because 18F is not exempt). 

But, it would wise for you to confirm that with whatever legal counsel the FEC has. 

My assumption for now will be that I don't need to provide any information about PRA, unless you hear from someone else that PRA is a concern for the FEC. 

Sound ok?

**Comment by AmyKort** [comment]
I believe we are exempt from the PRA. Could you send us information about how GSA handles ethnic anyway?

**Comment by nickykrause** [comment]
Meeting scheduled for Monday, 1/9

**Comment by nickykrause** [comment]
This will happen as a part of #49
