### ISSUE TITLE
Usability test training

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-transition#49]
Need to train FEC on how to conduct successful usability tests.

**Comment by adrianwebb** [comment]
Might be a duplicate of: https://github.com/18F/fec-transition/issues/46

**Comment by nickykrause** [comment]
@adrianwebb this seems like a duplicate of #46 and, to some extent, #45. I think we should close #46 and #45 in favor of this one (49) because it makes more sense to do these things as a training session and then to provide some take-home info (links to articles and stuff). 

I have set up a usability testing training session with @patphongs for Monday, 1/9.

**Comment by nickykrause** [comment]
Held 2-hour session with Pat today about usability testing and provided her with a list of resources for follow-up education / reference going forward

🎓 🎉
