### ISSUE TITLE
UX Handoff

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#67]
completion criteria?

**Comment by nickykrause** [comment]
Scheduled a "hand-off" meeting with Lauren and @patphongs for this week. Currently planning to go over some or all of the following:

- Talk through the nuts and bolts of usability testing. (This can be brief, or we can skip it entirely, since Lauren and Pat have been very involved in the process). I'll also be writing up something for the “read me” section of the testing repo that will document this more thoroughly.

- Walk through the Research archive on Google Drive. Talk through the folder structure — what’s all in there, and where do things live? what’s the best way to hand this off to the FEC?

- Review some of the Sketch files on my machine and zip them up to send to the FEC. (Note: Jen is the keeper of the latest Sketch files, but I have some old drafts and things that I will pass on nonetheless.)

- Review the current state of stuff that's in-progress (e.g., compliance map research; AO split pane viewer)

- Maybe look at some of the key GitHub issue-webs that are out there and have been iceboxed, just provide some background for things that might get picked up later on (e.g., legal filter designs) 

- Challenges I see coming up, if anything

**Comment by nickykrause** [comment]
We held a series of meetings and handed everything off, so this is done!
