### ISSUE TITLE
Design system training (how to design in fec-style)

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-transition#83]
Component of pattern library training
Jen develops training
Pat and John and Jim Jones
Lauren

**Comment by jenniferthibault** [comment]
Training part 1 happening tomorrow will include:

1. Intro to tools (Sketch, InVision)
2. Intro to FEC design files:
  - file structure, symbols, styles
3. File sharing/governance
4. (if time) prototyping in InVision

**Comment by jenniferthibault** [comment]
@patphongs @llienfec @johnnyporkchops 

Here's where you can install Sketch 43.2 (the version 18F runs) so that we can maintain file compatibility. I _believe_ that you'll be able to do this on a free trial, but not certain.
- https://www.sketchapp.com/updates/#version-43-2

I'm also going to send you a zipped collection of the sketch files.

## Additional trainings
**Getting started with Sketch:** -
- https://transition.fec.gov/pages/report_notices/2017/alsen.shtml#hour_48
**Getting started with InVision:**
- https://gsa.invisionapp.com/d/main/#/learn

Next steps are to start pairing on design issues

**Comment by jenniferthibault** [comment]
We're going to continue this through 1:1 pairings on design issues—closing.
