### ISSUE TITLE
Postgres Training

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-transition#88]
Postgres Training

PI board has this as an enhanced receipts and disbursements filter task. I've assigned it to technology transition

DBA level training on Postgres on AWS 

Jeff - fill in from PI planning participants.

**Comment by jwchumley** [comment]
Define needed postgres training. Assign to Wenchun

**Comment by PaulClark2** [comment]
Please find the lists below regarding PostgreSQL training, etc. 

- [ ] How to set up replication
- [ ] DB upgrade
- [ ] Restore if instance crash
- [ ] Create a DB link
- [ ] Select records from a table in one instance and insert them to a table in another instance.
- [ ] How to delete run away processors
- [ ] How to identify and kill dead locks
- [ ] More information about db tuning
- [ ] Current Database design guideline and documentation (for example: Nightly updating  processes logics for major forms and schedules tables)
- [ ] Steps to improve the data transferring rate from FECP database to Postgress database inCloud.gov when we have large amount of records in  busy  filing  periods. 
- [ ] More AWS, Python training
- [ ] 18F uses Celery to coordinate the workflow tasks.  Is it similar to the cron jobs we did on our server?  Do they use it to coordinate the database tasks as well?  How does it work?
- [ ] Yesterday Vraj was asking something about Alembic and SQLAlchemy models.  But he also mentioned they might move away from SQLAlchemy.  And something about a tool called rdbms-subsetter (which Carlo said was not working for a while) script that they used to generate their test data.  What are the role these tools played in supporting the database operation?  If they are to be decommissioned, what are their replacement (or what are the roles the replacement tools suppose to do?)

- [ ] How do we manage the PG database in AWS?

What are the contract agreement between 18F (and later would be our DB team) and Amazon?
 
We assume AWS will be responsible for system management such as database backup, space management, etc. Is this correct? 
If it is correct, in addition to the contract agreement, we would like to know what is the regular interaction mechanism between 18F (and later our DB team) and Amazon?
 
If this is not the case, we need to know how 18F manage the PG databases.
 
- [ ] How do they currently control the database design?

Currently we try to follow the theme that we transfer base tables data from FECP to PG (with exceptions if needed).  Then they create their tables/materialized views based on the data in the FECP base tables to fit their needs.
What is their current mechanism to coordinate the design of their ofec_xxxxx tables/MVs? 
Our understanding is for their web code development, they use GitHub branches merge to control the final version of code.  However, database objects such as tables/MVs are permanent structures in database and everyone share the same database, it can not be merged back to one table (please correct us if we are wrong) just like the code.  If there are no coordination mechanism, then we might ends of 10 code developer might have 10 different tables from the same base table with minor differences and DB ends up having to host quite a few copies of the same (similar) tables/MVs which are difficult and expensive to maintain. What is their current mechanism to coordinate the design of their ofec_xxxxx tables/MVs to avoid this situation? 
 
 
- [ ] The Database Design document for their current data flows (how their tables are populated by triggers/functions).  We don’t need step-by-step explain of the code in the function and triggers, but we will need an overall concept of the flow.

@ccostino @LindsayYoung @rjayasekera

**Comment by ccostino** [comment]
Thank you, @PaulClark2, this is a great list and we can start planning what to focus on!

**Comment by LindsayYoung** [comment]
I am rolling some of this into the infrastructure [training document](https://docs.google.com/document/d/1dPiq4-IFNkM7rDm0hNi6BsakGBtxDcj_U8P5ZFM0p9M/edit#heading=h.tltyhyocts10) mentioned in #77 

I took a first pass on the most important things we need to and put that into the training draft but wanted to annotate the original ticket below. I appreciate the amount of thought that went into this list and would like to follow up with DBAs on this. 

----
Please find the lists below regarding PostgreSQL training, etc. 

- [ ] How to set up replication **Terraform**
- [ ] DB upgrade **Terraform**
- [ ] Restore if instance crash **Terraform**
- [ ] Create a DB link **Postgres**
- [ ] Select records from a table in one instance and insert them to a table in another instance. **Postgres**
- [ ] How to delete run away processors **Postgres**
- [ ] How to identify and kill dead locks **Postgres**
- [ ] More information about db tuning **Postgres**
- [ ] Current Database design guideline and documentation (for example: Nightly updating  processes logics for major forms and schedules tables) **style guide**
- [ ] Steps to improve the data transferring rate from FECP database to Postgress database inCloud.gov when we have large amount of records in  busy  filing  periods. _(This is a long term goal and not really a training element. Some things are to refactor triggers to reduce their impact, and to reduce the duplicative data that is sent to reduce volume)_
- [ ] More AWS, Python training
- [ ] 18F uses Celery to coordinate the workflow tasks.  Is it similar to the cron jobs we did on our server?  Do they use it to coordinate the database tasks as well?  How does it work? _(This would be better as pairing rather than formal training)_
- [ ] Yesterday Vraj was asking something about Alembic and SQLAlchemy models.  But he also mentioned they might move away from SQLAlchemy.  And something about a tool called rdbms-subsetter (which Carlo said was not working for a while) script that they used to generate their test data.  What are the role these tools played in supporting the database operation?  If they are to be decommissioned, what are their replacement (or what are the roles the replacement tools suppose to do?)

- [ ] How do we manage the PG database in AWS? **Terraform**

What are the contract agreement between 18F (and later would be our DB team) and Amazon?
_(This is probably best handled by talking to coud.gov)_ 
 
We assume AWS will be responsible for system management such as database backup, space management, etc. Is this correct? 
If it is correct, in addition to the contract agreement, we would like to know what is the regular interaction mechanism between 18F (and later our DB team) and Amazon?
 _(This is probably best handled by talking to coud.gov. We are still figuring out the AWS accounts outside cloud.gov)_ 

If this is not the case, we need to know how 18F manage the PG databases.
 
- [ ] How do they currently control the database design? _(This is handled in the general release process. Code review etc.)_

Currently we try to follow the theme that we transfer base tables data from FECP to PG (with exceptions if needed).  Then they create their tables/materialized views based on the data in the FECP base tables to fit their needs.
What is their current mechanism to coordinate the design of their ofec_xxxxx tables/MVs? _(This is all in the https://github.com/18F/openFEC)_
Our understanding is for their web code development, they use GitHub branches merge to control the final version of code.  However, database objects such as tables/MVs are permanent structures in database and everyone share the same database, it can not be merged back to one table (please correct us if we are wrong) just like the code.  If there are no coordination mechanism, then we might ends of 10 code developer might have 10 different tables from the same base table with minor differences and DB ends up having to host quite a few copies of the same (similar) tables/MVs which are difficult and expensive to maintain. What is their current mechanism to coordinate the design of their ofec_xxxxx tables/MVs to avoid this situation?  _(We do manage the databases as code, through the 18/openFEC repo and the 18f/fec-infrastructure terraform repo. The changes to the tables are managed by sql code in a way that is reproducible and applied in our dev, stage and prod environments. People can use test databases to try out their work locally and there is further review as the PR is approved by another person on the team and lives in the repo for reference. There are additional checks as we create the staging release; Only then do we apply a DB change to master.)_
 
 
- [ ] The Database Design document for their current data flows (how their tables are populated by triggers/functions).  We don’t need step-by-step explain of the code in the function and triggers, but we will need an overall concept of the flow. _(The SSP has a pretty detailed documentation of flow, but we would love to improve documentation on the data side with FEC folks.)_
